In [7]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("student_depression_dataset.csv")

In [9]:
df.head

<bound method NDFrame.head of            id  Gender   Age           City Profession  Academic Pressure  \
0           2    Male  33.0  Visakhapatnam    Student                5.0
1           8  Female  24.0      Bangalore    Student                2.0
2          26    Male  31.0       Srinagar    Student                3.0
3          30  Female  28.0       Varanasi    Student                3.0
4          32  Female  25.0         Jaipur    Student                4.0
...       ...     ...   ...            ...        ...                ...
27896  140685  Female  27.0          Surat    Student                5.0
27897  140686    Male  27.0       Ludhiana    Student                2.0
27898  140689    Male  31.0      Faridabad    Student                3.0
27899  140690  Female  18.0       Ludhiana    Student                5.0
27900  140699    Male  27.0          Patna    Student                4.0

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                0.0  8.97                 2.0               0.0
1                0.0  5.90                 5.0               0.0
2                0.0  7.03                 5.0               0.0
3                0.0  5.59                 2.0               0.0
4                0.0  8.13                 3.0               0.0
...              ...   ...                 ...               ...
27896            0.0  5.75                 5.0               0.0
27897            0.0  9.40                 3.0               0.0
27898            0.0  6.61                 4.0               0.0
27899            0.0  6.88                 2.0               0.0
27900            0.0  9.24                 1.0               0.0

            Sleep Duration Dietary Habits      Degree  \
0              '5-6 hours'        Healthy     B.Pharm
1              '5-6 hours'       Moderate         BSc
2      'Less than 5 hours'        Healthy          BA
3              '7-8 hours'       Moderate         BCA
4              '5-6 hours'       Moderate      M.Tech
...                    ...            ...         ...
27896          '5-6 hours'      Unhealthy  'Class 12'
27897  'Less than 5 hours'        Healthy         MSc
27898          '5-6 hours'      Unhealthy          MD
27899  'Less than 5 hours'        Healthy  'Class 12'
27900  'Less than 5 hours'        Healthy         BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes               3.0
1                                        No               3.0
2                                        No               9.0
3                                       Yes               4.0
4                                       Yes               1.0
...                                     ...               ...
27896                                   Yes               7.0
27897                                    No               0.0
27898                                    No              12.0
27899                                   Yes              10.0
27900                                   Yes               2.0

      Financial Stress Family History of Mental Illness  Depression
0                  1.0                               No           1
1                  2.0                              Yes           0
2                  1.0                              Yes           0
3                  5.0                              Yes           1
4                  1.0                               No           0
...                ...                              ...         ...
27896              1.0                              Yes           0
27897              3.0                              Yes           0
27898              2.0                               No           0
27899              5.0                               No           1
27900              3.0                              Yes           1

[27901 rows x 18 columns]>

In [13]:

df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [14]:
df.columns = df.columns.str.strip()

In [45]:
X=df.iloc[:,0:1]
Y=df.iloc[:,-1]

In [46]:
X

           id
0           2
1           8
2          26
3          30
4          32
...       ...
27896  140685
27897  140686
27898  140689
27899  140690
27900  140699

[27901 rows x 1 columns]

In [17]:
X = df[["Academic Pressure", "Study Satisfaction", "Sleep Duration"]]
Y = df[["Depression"]]

In [47]:
Y

0        1
1        0
2        0
3        1
4        0
        ..
27896    0
27897    0
27898    0
27899    1
27900    1
Name: Depression, Length: 27901, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [15]:
from sklearn.linear_model import LinearRegression

In [50]:
lr = LinearRegression()

In [51]:
lr.fit(student_train,depression_train)

LinearRegression()

In [52]:
X_test

           id
1457     7494
3535    17742
20022  101405
9735    49137
5471    27585
...       ...
1353     6959
18563   94002
3909    19603
5616    28292
20191  102208

[5581 rows x 1 columns]

In [42]:
Y_test

1457     1
3535     1
20022    1
9735     0
5471     1
        ..
1353     1
18563    0
3909     0
5616     1
20191    1
Name: Depression, Length: 5581, dtype: int64

In [113]:
Y_pred = lr.predict(X_test.iloc[[2]])

In [2]:
plt.scatter(df["id"],df["Academic Pressure"])
plt.plot(X_test,lr.predict(X_test),color="red")
plt.xlabel("id")
plt.ylabel("Academic Pressure")

NameError: name 'plt' is not defined